name: ${project.name}
version: ${project.version}
main: de.TheJeterLP.Bukkit.SurvivalGames.SurvivalGames
author: TheJeterLP
description: Survival-Games plugin

commands:
    survivalgames:
        description: Survival Games Command
        usage: /sg <command> <args>
        aliases: [sg, hungergames, hg]

