name: ${project.name}
author: TheJeterLP
version: 1.0.0
description: CakePoke Game System

main: de.TheJeterLP.Bukkit.CakePoke.Bukkit.CakePoke

commands:
   cp:
       usage: |
        /<command> <finish> <id>
        /<command> <delete> <id>
        /<command> <create> <id> <maxplayers>
        /<command> <setspawn> <id> <spawn|lobby>
        /<command> <setsign> <id>