name: ${project.name}
author: TheJeterLP
version: ${project.version}
description: VirusSpleef Game System

main: de.TheJeterLP.Bukkit.VillagerHunt.Bukkit.VillagerHunt

commands:
   vh:
       usage: |
        /<command> <finish> <id>
        /<command> <delete> <id>
        /<command> <create> <id> <maxplayers>
        /<command> <setspawn> <id> <spawn|lobby>
        /<command> <setsign> <id>
        /<command> <restart> <id>